### ISSUE TITLE
Description for subcassfeatures tags

### ISSUE THREAD

**Issue by revilowaldow** [ineedanamepls/5eSchema#1]
Please can we get a nice description-y thingy in here https://github.com/ineedanamepls/5eSchema/blob/c731a0ca49d766b60c285124a1a4f1cc1e684acf/TheGiddyLimit%20TheGiddyLimit.github.io%20master%20test-schema/class.json#L206 (or wherever it needs to be) saying it needs to be in the form `"<name>|<className>|<classSource>|<subclassShortName>|<subclassSource>|<level>|<source>"`

**Comment by ineedanamepls** [comment]
Alrighty ill get on it when i have time

**Comment by ineedanamepls** [comment]
Put them in for `classFeatures` and `subclassFeatures`.

**Comment by revilowaldow** [comment]
Woozy pleading joy face 🥺😍😂🥴
