### ISSUE TITLE
Intro and Outro for Tables

### ISSUE THREAD

**Issue by revilowaldow** [ineedanamepls/5eSchema#4]
The `"intro"` and `"outro"` items are missing from tables.json.

See Giddy's Example brew for examples: 
Intro: 
https://github.com/TheGiddyLimit/homebrew/blob/1d396e2efc4f850c53ee1a4f4eb26ba51e8c09c9/table/Sample%20-%20Giddy%3B%20Murder%20Evidence.json#L23
Outro: 
https://github.com/TheGiddyLimit/homebrew/blob/1d396e2efc4f850c53ee1a4f4eb26ba51e8c09c9/table/Sample%20-%20Giddy%3B%20Murder%20Evidence.json#L27

This repo:
https://github.com/ineedanamepls/5eSchema/blob/7e3de6a03848e4a51cf684a26c294b2c6c4dfc94/TheGiddyLimit%20TheGiddyLimit.github.io%20master%20test-schema/tables.json#L9

**Comment by ineedanamepls** [comment]
donesies
